from decouple import config
GATEWAY_UID = config("GATEWAY_UID")
HELIUM_PUBKEY = config("HELIUM_PUBKEY")

PROXY_HOST = config("PROXY_HOST")
PROXY_PORT = config("PROXY_PORT", cast=int)

MINER_HOST = config("MINER_HOST")
MINER_PORT = config("MINER_PORT", cast=int)

#NO_MULTI_BROADCASTS = config("NO_MULTI_BROADCASTS", cast=bool, default=False)

HELIUMOVER_API_KEY = config("HELIUMOVER_API_KEY")
HELIUMOVER_API_UPSTREAM = config("HELIUMOVER_API_UPSTREAM")
HELIUMOVER_API_DOWNSTREAM = config("HELIUMOVER_API_DOWNSTREAM")
HELIUMOVER_API_HOTSPOT = config("HELIUMOVER_API_HOTSPOT")