"""hotspot apikey

Revision ID: 7c1f53944c8c
Revises: dd8cff14b5d0
Create Date: 2022-06-14 03:38:43.396912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c1f53944c8c'
down_revision = 'dd8cff14b5d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotspot', sa.Column('api_key', sa.String(length=36), nullable=False))
    op.create_unique_constraint(None, 'hotspot', ['api_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hotspot', type_='unique')
    op.drop_column('hotspot', 'api_key')
    # ### end Alembic commands ###
