"""move api key to group

Revision ID: 967f683c634a
Revises: 7c1f53944c8c
Create Date: 2022-06-14 04:11:10.953926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '967f683c634a'
down_revision = '7c1f53944c8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('hotspot_api_key_key', 'hotspot', type_='unique')
    op.drop_column('hotspot', 'api_key')
    op.add_column('proxy_group', sa.Column('api_key', sa.String(length=36), nullable=False))
    op.create_unique_constraint(None, 'proxy_group', ['api_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'proxy_group', type_='unique')
    op.drop_column('proxy_group', 'api_key')
    op.add_column('hotspot', sa.Column('api_key', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.create_unique_constraint('hotspot_api_key_key', 'hotspot', ['api_key'])
    # ### end Alembic commands ###
