"""hotspot lat lng gain

Revision ID: dd8cff14b5d0
Revises: 377b401ff600
Create Date: 2022-06-11 19:40:39.530923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd8cff14b5d0'
down_revision = '377b401ff600'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotspot', sa.Column('lat', sa.Float(precision=53), nullable=False))
    op.add_column('hotspot', sa.Column('lng', sa.Float(precision=53), nullable=False))
    op.add_column('hotspot', sa.Column('gain', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotspot', 'gain')
    op.drop_column('hotspot', 'lng')
    op.drop_column('hotspot', 'lat')
    # ### end Alembic commands ###
